### ISSUE TITLE
`raster` package masks `dplyr::select`

### ISSUE THREAD

**Issue by wolfeclw** [erikarasnick/ecat#3]
does `raster` need to be loaded to the global env?  could be frustrating if `dplyr::select` is used in previous code and you would like to rerun the ecat calculation after including other variables in the data frame

**Comment by cole-brokamp** [comment]
this is a known issue and it seems that raster is loaded even when we don't `library()` call it and just invoke it with `raster::...()`. unfortunately, i think the best case scenario is what we came up with, which was to just give the user a loud warning every time they use it.
